
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='calc-interpreter',
    version='0.1.0',
    python_requires='==3.*,>=3.8.3',
    author='Dominik Nedvedik',
    author_email='dominik.nedvedik@protonmail.com',
    packages=['calc_interpreter'],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
    extras_require={"dev": ["dephell==0.*,>=0.8.3", "pylint==2.*,>=2.5.3", "pytest==5.*,>=5.4.3", "pytest-cov==2.*,>=2.10.0"]},
)
